config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "cocktails#index"
  resources :cocktails, only: [:new, :show, :create, :destroy] do
    resources :doses, only: [:new, :create]
  end
  resources :doses, only: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  validates :name, uniqueness: true, presence: true

  mount_uploader :photo, PhotoUploader
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :ingredient
  belongs_to :cocktail

  validates :description, presence: true
  validates :ingredient_id, uniqueness: { scope: :cocktail_id }
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  validates :name, uniqueness: true, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  def index
    @cocktails = Cocktail.all
  end

  def new
    @cocktail = Cocktail.new
  end

  def show
    @cocktail = Cocktail.find(params[:id])
  end

  def create
    @cocktail = Cocktail.create(cocktail_params)
    if @cocktail.valid?
      redirect_to @cocktail
    else
      render :new
    end
  end

  def destroy
    @cocktail = Cocktail.find(params[:id])
    @cocktail.destroy
    redirect_to root_path
  end

  private

  def cocktail_params
    params.require(:cocktail).permit(:name, :photo)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  before_action :set_cocktail, only: [:new, :create]

  def new
    @dose = Dose.new
  end

  def create
    @dose = Dose.new(dose_params)
    @dose.cocktail = @cocktail
    @dose.save
    if @dose.save
      redirect_to @cocktail
    else
      render :new
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @cocktail = @dose.cocktail
    @dose.destroy
    redirect_to @cocktail
  end

  private

  def set_cocktail
    @cocktail = Cocktail.find(params[:cocktail_id])
  end

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/cocktails/index.html.erb
<div class="col-8">
  <h1>CHOOSE YOUR COCKTAIL</h1>
  <div class="cards">
    <% @cocktails.each do |cocktail| %>
      <div class="card-category" style = "background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path cocktail.photo, height: 200, width: 250, crop: :scale%>');">
        <%= link_to  cocktail.name , cocktail_path(cocktail.id) %>
        <%= link_to "+", cocktail_path(cocktail.id), class: "delete_link", method: :delete %>
      </div>
    <% end %>
  </div>
</div>

app/views/cocktails/new.html.erb
<div class="col-8">
  <h1>Add a cocktail</h1>
  <%= simple_form_for @cocktail do |f| -%>
    <%= f.input :name %>
    <%= f.input :photo %>
    <%= f.input :photo_cache, as: :hidden %>
    <%= f.button :submit, class: "btn btn-outline-primary" %>
  <% end -%>
</div>

app/views/cocktails/show.html.erb
<div class="col-10 d-flex flex-column ">
  <div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.3),rgba(0,0,0,0.3)), url('<%= cl_image_path @cocktail.photo, width: 200, height: 400 %>');">
    <div class="container d-flex justify-content-center">
      <h1><%= @cocktail.name %></h1>
    </div>
  </div>
  <div class="list_ingredient flex-grow-1 ">
    <h2>List of Ingredients</h2>
    <ul>
    <% @cocktail.doses.each do |dose| %>
      <li>
        <strong><%= dose.ingredient.name %></strong> <%= dose.description %>   <%= link_to '<i class="fas fa-trash-alt"></i>'.html_safe, dose_path(dose), method: :delete %>
      </li>
    <% end %>
    </ul>
  </div>
  <div class="link d-flex justify-content-between">
    <%= link_to "Back to List", root_path, class: "btn btn-outline-primary" %>
    <%= link_to "add a ingredient", new_cocktail_dose_path(@cocktail.id), class: "btn btn-outline-primary"  %>
  </div>
</div>

app/views/doses/create.html.erb
<h1>Doses#create</h1>
<p>Find me in app/views/doses/create.html.erb</p>

app/views/doses/delete.html.erb
<h1>Doses#delete</h1>
<p>Find me in app/views/doses/delete.html.erb</p>

app/views/doses/new.html.erb
<div class="col-8">
  <%= simple_form_for [@cocktail, @dose] do |f| -%>
    <div class="form-group">
      <%= f.association :ingredient , input_html:  { class: "select2" } %>
      <%= f.input :description ,class: "form-control"%>
    </div>
      <%= f.button :submit, class: "btn btn-outline-primary" %>
  <% end -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light sticky-top px-3">
      <a class="navbar-brand" href= "/">750cL</a>
      <div class="ml-auto flex" >
        <a class="btn btn-outline-primary" href= "/cocktails/new">Add Cocktail</a>
      </div>
    </nav>
    <div class="container bg-white h-100">
      <div class="row justify-content-center h-100">
          <%= yield %>
      </div>
    </div>
    <%= stylesheet_pack_tag 'application' %>
    <%= javascript_pack_tag "application" %>
  </body>
</html>